# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Kuhn"
license = "GNU General Public License v2.0"
licenselink = "https://github.com/gtenham/KuhnForHugo/blob/master/LICENSE.md"
description = "Theme featuring CSS Grid layouts via aggressive progressive enhancement"
homepage = "http://www.gertontenham.nl/"
tags = ["blog","responsive"]
features = ["CSS Grid layouts"]
min_version = "0.38"

[author]
  name = "Gerton ten Ham"
  homepage = "http://www.gertontenham.nl/"

# If porting an existing theme
[original]
  name = "Kuhn"
  homepage = "https://mor10.com/"
  repo = "https://github.com/mor10/kuhn"
